baseURL = "https://www.biggins.tech/"
languageCode = "en-us"
title = "biggins"
theme = "minimal"
disqusShortname = "jjbiggins" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Joe Biggins"
    description = "always curious"
    githubUsername = "#"
    accent = "red"
    #accent = "black"
    showBorder = false
    backgroundColor = "#292a2d"
    textColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python", "c", "java", "go", "haskell", "kotlin", "scala", "swift"]



[[menu.main]]
    url = "/"
    name = "home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "blog"
    weight = 3

#[[menu.main]]
#    url = "/project/"
#    name = "projects"
#    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.



[[menu.icon]]
    url = "mailto:joe+contacts@biggins.tech"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jjbiggins/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/_joebiggins/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/josephbiggins/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/josephbiggins/"
    name = "fab fa-stack-overflow"
    weight = 5
